FORMAT: 1A

# Listen Together(v4)

Allow kkbox members to view listen-together pages and follow hosts

# Group Host

<!-- include(blueprint/host.apib) -->

# Group Follow

<!-- include(blueprint/follow.apib) -->